name: model-training-framework
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.12

  # Core ML libraries
  - pytorch>=2.0.0
  - numpy>=1.21.0

  # Build tools
  - pip
  - setuptools
  - wheel

  # Development tools
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - pytest-mock>=3.8.0
  - ruff>=0.1.0

  # Pip dependencies not available in conda
  - pip:
    - lightning-fabric>=2.0.0
    - gitpython>=3.1.0
    - dataclasses-json>=0.5.0
    - typing-extensions>=4.0.0
    - colorlog>=6.0.0
    - pyyaml>=6.0
    - wandb>=0.13.0
    - mypy>=0.991
    - pre-commit>=2.20.0

    # Install the package in editable mode
    - -e .
