# Preemption and Fault Tolerance Configuration
# This configuration demonstrates advanced preemption handling and fault tolerance
# for production ML training in environments with job preemption and interruptions.

experiment_name: "fault_tolerant_production_training"
description: "Advanced fault tolerance with preemption handling and automatic recovery"

# Model configuration optimized for checkpointing
model:
  name: "resilient_transformer"
  hidden_size: 512
  num_layers: 8
  num_heads: 8
  intermediate_size: 2048
  dropout_rate: 0.1

  # Fault tolerance optimizations
  gradient_checkpointing: true  # Reduce memory for faster checkpointing
  activation_checkpointing: true
  use_cache: false             # Disable for deterministic behavior

# Training configuration for fault tolerance
training:
  epochs: 100
  batch_size: 64
  learning_rate: 1e-4
  gradient_accumulation_steps: 2
  gradient_clip_norm: 1.0

  # Deterministic training for reproducible recovery
  seed: 42
  deterministic: true
  benchmark: false             # Disable for deterministic behavior

  # Frequent evaluation for progress tracking
  evaluation_strategy: "steps"
  eval_steps: 500
  save_strategy: "steps"
  save_steps: 250              # Frequent saves for fault tolerance
  logging_steps: 50

# Dataset configuration with caching for fast recovery
data:
  dataset_name: "cached_production_data"
  train_split: "train"
  val_split: "validation"

  # Caching for fast restart
  cache_dir: "./data_cache"
  load_from_cache_file: true
  preprocessing_num_workers: 8

  # Data integrity
  verify_data_integrity: true
  backup_data_locally: true

# Optimizer with state preservation
optimizer:
  name: "adamw"
  learning_rate: 1e-4
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8

# Learning rate scheduler state preservation
scheduler:
  name: "cosine"
  warmup_steps: 1000
  min_lr: 1e-7

  # State tracking for recovery
  save_scheduler_state: true
  restore_scheduler_state: true

# SLURM configuration for preemptible environments
slurm:
  job_name: "fault_tolerant_training"
  time_limit: "24:00:00"
  nodes: 1
  ntasks_per_node: 2
  cpus_per_task: 8
  mem: "128G"
  gres: "gpu:2"
  partition: "preemptible"      # Use preemptible partition for cost savings

  # Preemption handling
  signal: "SIGUSR1@300"        # 5-minute warning signal
  requeue: true                # Allow automatic requeuing
  array: null                  # Can be used for array jobs

  # Job dependencies and chaining
  dependency: null             # afterok:jobid for job chains
  begin: null                  # Schedule job start time

# Advanced logging for fault analysis
logging:
  log_level: "INFO"
  use_wandb: true
  wandb_project: "fault_tolerant_training"
  wandb_tags: ["fault_tolerance", "preemption", "production"]

  # Detailed fault logging
  log_system_events: true
  log_signal_handling: true
  log_checkpoint_operations: true
  log_recovery_operations: true

  # External logging for analysis
  send_to_external_logger: false
  external_logger_endpoint: "https://logs.company.com/api/events"

# Comprehensive checkpointing strategy
checkpoint:
  # Frequent checkpointing for minimal data loss
  save_every_n_epochs: 1
  save_every_n_steps: 250
  save_best_only: false        # Keep all for recovery analysis

  # Complete state preservation
  save_optimizer_states: true
  save_scheduler_state: true
  save_rng_state: true         # Critical for deterministic recovery
  save_model_state: true
  save_training_state: true

  # Advanced checkpoint management
  checkpoint_dir: "./fault_tolerant_checkpoints"
  max_checkpoints: 20          # Keep more for analysis
  checkpoint_format: "pytorch" # or "safetensors"
  async_save: true             # Non-blocking saves

  # Emergency checkpointing
  emergency_checkpoint_on_signal: true
  emergency_checkpoint_timeout: 60  # seconds

  # Checkpoint verification
  verify_checkpoint_integrity: true
  test_checkpoint_loading: true

  # Backup strategies
  create_backup_copies: true
  backup_to_shared_storage: true
  backup_compression: true

# Preemption and signal handling
preemption:
  # Signal configuration
  timeout_minutes: 300         # 5 hours before hard timeout
  grace_period_seconds: 300    # 5 minutes for cleanup
  warning_time_seconds: 300    # 5 minutes warning

  # Signal handling
  handle_sigusr1: true         # SLURM preemption signal
  handle_sigterm: true         # Termination signal
  handle_sigint: true          # Interrupt signal (Ctrl+C)
  handle_sighup: true          # Hang up signal

  # Recovery behavior
  save_on_signal: true
  cleanup_on_signal: true
  resume_from_checkpoint: true
  auto_restart: false          # Depend on SLURM requeue

  # Retry logic
  max_retries: 5
  retry_delay_seconds: 30
  exponential_backoff: true

  # State preservation during preemption
  preserve_random_state: true
  preserve_optimizer_state: true
  preserve_scheduler_state: true
  preserve_model_state: true
  preserve_training_metrics: true

# Monitoring and alerting for fault detection
monitoring:
  # System monitoring
  monitor_gpu_memory: true
  monitor_cpu_usage: true
  monitor_disk_usage: true
  monitor_network_connectivity: true

  # Training monitoring
  monitor_loss_divergence: true
  monitor_gradient_norms: true
  monitor_learning_rate: true
  monitor_training_speed: true

  # Fault detection
  detect_nan_gradients: true
  detect_inf_loss: true
  detect_memory_leaks: true
  detect_slow_progress: true

  # Health checks
  health_check_interval: 300   # 5 minutes
  heartbeat_interval: 60       # 1 minute

  # Alerting thresholds
  memory_usage_threshold: 0.9
  loss_divergence_threshold: 10.0
  training_speed_threshold: 0.1  # Relative to expected speed

# Recovery and resume configuration
recovery:
  # Automatic recovery
  auto_resume_on_restart: true
  resume_from_latest_checkpoint: true
  validate_checkpoint_before_resume: true

  # Recovery strategies
  recovery_mode: "exact"       # "exact", "approximate", "adaptive"
  fallback_to_earlier_checkpoint: true
  max_checkpoint_age_hours: 24

  # State validation during recovery
  validate_model_state: true
  validate_optimizer_state: true
  validate_rng_state: true
  validate_training_metrics: true

  # Recovery logging
  log_recovery_process: true
  log_state_differences: true
  log_performance_impact: true

# Fault injection for testing (development only)
fault_injection:
  enabled: false               # Set to true for testing

  # Simulated failures
  simulate_preemption: false
  simulate_oom: false
  simulate_network_failure: false
  simulate_disk_full: false

  # Failure timing
  failure_probability: 0.01    # 1% chance per step
  failure_after_steps: null    # Fixed step for failure
  failure_after_time: null     # Fixed time for failure

# Performance optimization for fault tolerance
performance:
  # Memory management
  clear_cache_on_checkpoint: true
  optimize_memory_usage: true
  use_memory_efficient_attention: true

  # Checkpoint optimization
  compress_checkpoints: true
  use_fast_checkpoint_format: true
  parallel_checkpoint_saving: true

  # Training optimization
  compile_model: false         # Disable for deterministic behavior
  use_fast_attention: false    # May affect determinism
  optimize_for_inference: false

# Testing and validation
testing:
  # Checkpoint testing
  test_checkpoint_save_load: true
  test_recovery_determinism: true
  test_signal_handling: true

  # Fault tolerance testing
  run_fault_tolerance_tests: false  # Set to true for validation
  test_preemption_handling: false
  test_memory_pressure: false

  # Performance testing
  benchmark_checkpoint_speed: false
  benchmark_recovery_speed: false

# Compliance and audit
audit:
  # Training audit
  log_all_training_events: true
  track_data_lineage: true
  record_model_versions: true

  # Fault audit
  log_all_failures: true
  log_recovery_actions: true
  track_downtime: true

  # Compliance
  maintain_audit_trail: true
  retention_period_days: 365

# Environment-specific settings
environments:
  development:
    checkpoint.save_every_n_steps: 50
    preemption.timeout_minutes: 30
    fault_injection.enabled: true
    testing.run_fault_tolerance_tests: true

  staging:
    checkpoint.save_every_n_steps: 100
    preemption.timeout_minutes: 120
    monitoring.health_check_interval: 180

  production:
    monitoring.monitor_gpu_memory: true
    monitoring.detect_memory_leaks: true
    audit.log_all_training_events: true
    checkpoint.verify_checkpoint_integrity: true
