# Simple configuration for a single DataLoader using the multi-dataloader API

# Multi-dataloader configs (split by phase)
train_loader_config:
  sampling_strategy: "sequential"        # For single loader
  epoch_length_policy: "sum_of_lengths"  # Use all data
  dataloader_names: ["main"]             # Single name in list

val_loader_config:
  sampling_strategy: "sequential"
  dataloader_names: ["main_val"]

# Validation behavior
validation:
  frequency: "per_epoch"
  aggregation: "micro_avg_weighted_by_samples"

# Logging
logging:
  logger_type: "console"
  log_scalars_every_n_steps: 10

# Checkpointing
checkpoint:
  save_every_n_epochs: 2
  max_checkpoints: 3

# Performance
performance:
  gradient_accumulation_steps: 1
  use_amp: false
  clip_grad_norm: 1.0
